/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { College } from './types';

export const COLLEGES: College[] = [
  {
    id: 'ajeenkya',
    name: 'Ajeenkya DY Patil University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 10th 2026',
    region: 'West',
    state: 'Maharashtra',
    city: 'Pune',
    address: 'DY Patil Knowledge City Road Via Lohgaon, Airport Rd, Charholi Budruk, Pune, Maharashtra 412105',
    lat: 18.6186,
    lng: 73.9262,
    mapUrl: 'https://www.google.com/maps/place/Ajeenkya+DY+Patil+University/data=!4m2!3m1!1s0x0:0x51ca0d931361c1bc?sa=X&ved=1t:2428&ictx=111',
    programsCount: 4,
    learnerIntake: 360,
    brochureLink: 'https://drive.google.com/file/d/1OEBTZCXA59nGPFLpmL1kTcl-5GXXRRK_/view?usp=drive_link',
    campusVideo: 'https://www.youtube.com/embed/mNiHkHQkF0A',
    registrationFee: '1,500 INR Application Fee | Booking Fee: 20k to 50k - seat booking Fee',
    bridgeFee: '30,000 INR Non-Refundable Bridge Fee',
    programFee: 'Allied Health Sciences (AHP) - 8.0L total',
    annualFee: 2.0,
    totalProgramFee: 8.0,
    paymentLink: 'https://admissions.adypu.edu.in/',
    paymentCycle: 'Semesters: 1 Lakh per semester (8 semesters)',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Respiratory Technology (B.RT)'
    ],
    universityOwner: 'Dipanjana Saha (9022565526)',
    campusManager: 'Siddhesh (9850238514)',
    hostelAvailable: 'Yes. Girls & Boys Hostel (Minimum fee 90,000 INR, Maximum fee 1,50,000 INR per year)',
    amenity: 'Hostel Includes GYM, Electricity, Water, Food, Induction, Geyser, Wifi, Bus Charges (15k to 30k)',
    transportation: 'Yes. Decided by distance and route coverage',
    roi: 'Average package 7 LPA',
    avgPlacementPackage: 7.0,
    uniquePoints: 'The Best Private University of the Year 2018 by ASSOCHAM. Best Education Brand 2018-19 by Economic Times. Education Technology Innovation Award for Competency-based Transcript System.',
    loanDetails: 'Yes (ICICI Bank. If student needs documents to apply with a different bank, they will provide the documents)',
    scholarshipDetails: 'State or National scholarship applicable, standard portal eligibility',
    fstStaff: 'Maya Sharma (9131449122) / Aniket Bandre (8149667956) / Anjali Ingale (9309909538)',
    ismManager: 'Ankit'
  },
  {
    id: 'alard',
    name: 'Alard University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 20th 2026',
    region: 'West',
    state: 'Maharashtra',
    city: 'Pune',
    address: 'ALARD Knowledge Park, Survey No. 47 and 50, Near Rajiv Gandhi IT Park, Marunji, Hinjawadi, Pune 411 057',
    lat: 18.5782,
    lng: 73.7441,
    mapUrl: 'https://maps.app.goo.gl/vZSqwKSECtxBNgJP7',
    programsCount: 5,
    learnerIntake: 300,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/u76anD4BQsY',
    registrationFee: '1,000 INR Application | Booking: 30k + 30k Bridge Course',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP: 8.0L | BPT: 10.0L',
    annualFee: 2.0,
    totalProgramFee: 8.0,
    paymentLink: 'Offline/On-Campus Accounts Desk',
    paymentCycle: 'Annual Tuition Fee Structure',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP) | 4+1 Years (BPT)',
    eligibility: 'Pass 10+2 with PCB (Minimum 50% Marks in Bio/Sciences)',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)',
      'Bachelor of Physiotherapy (BPT)'
    ],
    universityOwner: 'Dipanjana Saha (9022565526)',
    campusManager: 'Vinit Karande (9920984284)',
    hostelAvailable: 'Yes (Boys/Girls accommodations from 75,000 to 1,00,000 INR per year)',
    amenity: 'High-tech AI & Robotics labs, Central library with e-resources, Wi-Fi enabled smart classrooms, Scenic 5-star campus with solar power, Specialized clubs like Ikebana & Culinary Arts',
    transportation: 'Yes, city-wide Pune and Hinjawadi routes',
    roi: 'Average package 6.0 LPA',
    avgPlacementPackage: 6.0,
    uniquePoints: 'Located directly near Pune’s Hinjawadi Rajiv Gandhi IT Park - excellent industry-academic projects and training facilities.',
    loanDetails: 'No direct loan facility (Bonafide certificate provided for education loan processing)',
    scholarshipDetails: 'State or National scholarship applicable',
    fstStaff: 'Manoj Sharma (7798514159) / Kishor Galande (9975751963)',
    ismManager: 'N/A'
  },
  {
    id: 'universal-skilltech',
    name: 'Universal SkillTech University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'After 10th February',
    region: 'West',
    state: 'Maharashtra',
    city: 'Vasai',
    address: 'Universal Campus, Near Bhajanlal Dairy, Kaman, Bhiwandi Road, Vasai - 401208, Maharashtra',
    lat: 19.3504832,
    lng: 72.9169588,
    mapUrl: 'https://www.google.com/maps/place/Universal+SkillTech+University/@19.3504882,72.9143839,17z/',
    programsCount: 5,
    learnerIntake: 300,
    brochureLink: 'https://drive.google.com/file/d/1Bey2nkKHe2gkMjOsJJgAijocvYSJZh9r/view?usp=drive_link',
    campusVideo: 'https://www.youtube.com/embed/XG7d-UUQqqg',
    registrationFee: 'Application Fee is INR 2,000 | Booking Fees 50k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP: 7.2L (4 Years) | BPT: 9.0L (5 Years) | BBA: 6.0L (3 Years)',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'Universal SkillTech Accounts Counter',
    paymentCycle: 'Tuition: (1st to 3rd term) 2,20,000 INR Per Year (till 6th semester), 4th Year is 0 tuition',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP) | 4+1 Years (BPT) | 3 Years (BBA)',
    eligibility: '10+2 PCB with 50% minimum aggregate, no entrance test required',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (B.MLS)',
      'Bachelor of Physiotherapy (BPT)',
      'BBA - Hospitality and Global Tourism'
    ],
    universityOwner: 'Dipanjana Saha (9022565526)',
    campusManager: 'Vinit Karande (9920984284)',
    hostelAvailable: 'Yes Available (1 Lakh to 2 Lakhs per year depending on sharing level)',
    amenity: 'WiFi, Laundry, Food, Play Area, modern diagnostic practice labs, fully specialized robotics labs',
    transportation: 'Yes. Transportation charges are ₹17,000 per year',
    roi: 'Average placement package: 5–6 LPA with 550+ company placement network',
    avgPlacementPackage: 5.5,
    uniquePoints: 'First-of-its-kind high-tech campus with solar power, massive academic arrays, and outstanding placement options with 550+ corporate tie-ups.',
    loanDetails: 'Education loan support via bonafide certificate',
    scholarshipDetails: 'State or National/Minority scholarship applicable',
    fstStaff: 'Pawan Pandey (8459497735) / Sneha Raghu Jadhav (7977486221)',
    ismManager: 'Ankit'
  },
  {
    id: 'sanjivani',
    name: 'Sanjivani University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 2026',
    region: 'West',
    state: 'Maharashtra',
    city: 'Kopargaon',
    address: 'Sanjivani University, Kopargaon, Near Shirdi, Ahilyanagar (Ahmednagar), 423601',
    lat: 19.9010491,
    lng: 74.4949188,
    mapUrl: 'https://www.google.com/maps/place/Sanjivani+University/@19.9010491,74.4949188',
    programsCount: 5,
    learnerIntake: 300,
    brochureLink: 'https://drive.google.com/file/d/1BR_UWL8alT3cHPF-0TkmVhVkuOoiaWCE/view?usp=sharing',
    campusVideo: 'https://www.youtube.com/embed/thBG6VIutp8',
    registrationFee: 'Application Fee is INR 500 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP: 8.0L (CVT, RT, Radiology, Dialysis) | BPT: 10.0L',
    annualFee: 2.0,
    totalProgramFee: 8.0,
    paymentLink: 'Offline/On-Campus Bank Desk',
    paymentCycle: 'Semesters basis: Divided into annual fee collect cycle',
    naacGrading: 'Applied',
    duration: '3+1 Years (AHP) | 4+1 Years (BPT)',
    eligibility: '10+2 Biology space with 50% PCB minimum',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)',
      'Bachelor of Physiotherapy (BPT)'
    ],
    universityOwner: 'Dipanjana Saha (9022565526)',
    campusManager: 'Kedar Ayachit (9881199224)',
    hostelAvailable: 'Yes Girls & Boys Hostel (Minimum fee 90,000 INR, Maximum fee 1,50,000 INR per year)',
    amenity: 'Central e-resources library, high-tech AI laboratories, solar-powered campus blocks, multi-cuisine cafeteria, football & basketball courts',
    transportation: 'Yes, university-operated transport system',
    roi: 'Average package 5.5 LPA with 550+ company placement network',
    avgPlacementPackage: 5.5,
    uniquePoints: 'Lush green state-of-the-art campus with first-class infrastructure, excellent research blocks, and top-class healthcare partner support.',
    loanDetails: 'Yes, they give Bonafide letter, Vidyalakshmi Loan',
    scholarshipDetails: 'State or national scholarship portal application',
    fstStaff: 'Shivani Sali (8080930589)',
    ismManager: 'Ankit'
  },
  {
    id: 'medicaps',
    name: 'MediCaps University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 5th 2026',
    region: 'West',
    state: 'Madhya Pradesh',
    city: 'Indore',
    address: 'AB Road Pigdamber, Rau, Indore, Madhya Pradesh 453331',
    lat: 22.6210224,
    lng: 75.8035907,
    mapUrl: 'https://www.google.com/maps/place/Medicaps+University+-+Private+University+in+Indore/@22.6210273,75.8010158',
    programsCount: 5,
    learnerIntake: 300,
    brochureLink: 'https://drive.google.com/file/d/147xh3ywD18WwSZsyUp11fnHPceC0qMUC/view?usp=drive_link',
    campusVideo: 'https://www.youtube.com/embed/Da1s-Q8ie-8',
    registrationFee: 'Application Fee - 1000 INR | Seat Booking Fee - 25,000 INR',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'A&OTT: 7.2L | CVT : 7.2L | MLT : 6.4L | MRIT : 6.4L | BBA : 7.2L | Forensic : 6.4L',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'https://admissions.medicaps.ac.in/',
    paymentCycle: 'Semester-wise (Per Annum 260000/- Fees will be collected in 3 years)',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Science with 50% marks in PCB/PCMB',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)',
      'Bsc in Forensics'
    ],
    universityOwner: 'Dipanjana Saha (9022565526)',
    campusManager: 'Rishabh Rai (9669518119)',
    hostelAvailable: 'Yes (1,60,000/-) Per Annum',
    amenity: 'Internal and outground sports grounds, Dance/Act Clubs, free Wifi, fully AC rooms, fully advanced research labs, library, transport lines',
    transportation: '50,000/yearly (semester wise payment) covering all corners of the city',
    roi: 'Average package of the university is 6.5 LPA over a lush 53-acre campus',
    avgPlacementPackage: 6.5,
    uniquePoints: '25 Years of Academic Excellence, Recognized as Madhya Pradeshs top private brand with 15k+ successful placements.',
    loanDetails: 'ICICI bank, IDFC first bank, Axis Bank, tie-up with various NBFCs, Vidyalakshmi Loan',
    scholarshipDetails: 'State or National scholarship applicable',
    fstStaff: 'Girish Kulkarni (8839619779) / Chanchal Shrivas (9575262354)',
    ismManager: 'Ankit'
  },
  {
    id: 'amet',
    name: 'AMET University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 15th 2026',
    region: 'South',
    state: 'Tamil Nadu',
    city: 'Chennai',
    address: '135, East Coast Road, Kanathur, Reddykuppam, Chennai, Tamil Nadu 603112',
    lat: 12.8682,
    lng: 80.2241,
    mapUrl: 'https://maps.app.goo.gl/9yG6LAm94qfW28Ew5',
    programsCount: 4,
    learnerIntake: 240,
    brochureLink: 'https://drive.google.com/file/d/130iQA7GwUChR3IZzkfkgYqFxHF3ndkd5/view?usp=drive_link',
    campusVideo: 'https://www.youtube.com/embed/fD3qZ_Z7yos',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 30k',
    bridgeFee: '25,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Courses: 6.8L - 7.5L Total',
    annualFee: 1.7,
    totalProgramFee: 6.8,
    paymentLink: 'https://www.ametuniv.ac.in/',
    paymentCycle: 'Yearly/Semester installment options',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 with PCB (Minimum 50% Marks in Biology and overall physical sciences)',
    programsList: [
      'Bachelor of Medical Laboratory Science (B.MLS)',
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Renal Dialysis Technology (B.RDT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Boys & Girls hostile space from 85k per year)',
    amenity: 'Equipped state-of-the-art simulation decks, oceanic modeling cells, RO water, playgrounds, gymnasium, full medical assistance room',
    transportation: 'Yes, route coverage across Chennai ECR lines',
    roi: 'Average placement packages ~5.5 LPA',
    avgPlacementPackage: 5.5,
    uniquePoints: 'India’s pioneer maritime and educational institute - exceptional focus on multi-disciplinary diagnostic training, safety drills, and corporate tie-ups.',
    loanDetails: 'Nationalized bank supporting bonafide letters',
    scholarshipDetails: 'NSP Portal state schemes',
    fstStaff: 'Suganya (7639094290) / Abdul Hadhi (7010730078) / Lakshmi A (6369899463)',
    ismManager: 'Ankit'
  },
  {
    id: 'st-peters-chennai',
    name: "St. Peter's Institute of Higher Education and Research - Chennai",
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 10th 2026',
    region: 'South',
    state: 'Tamil Nadu',
    city: 'Chennai',
    address: 'Tonakela Camp Road, Avadi, Chennai, Tamil Nadu 600054',
    lat: 13.1182,
    lng: 80.1141,
    mapUrl: 'https://maps.app.goo.gl/StPetersChennai',
    programsCount: 4,
    learnerIntake: 240,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5UshIlyY4jA',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Program fee: 7.2L (Total)',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'St Peters Accounts Desk, Chennai',
    paymentCycle: 'Tuition paid in equal annual installments',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Cardiovascular Technology (CVT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Separate Girls and Boys hostels, 90,000 INR per year)',
    amenity: 'Clinical internship tie-ups with leading hospitals, multi-cuisine cafeteria, high-speed Wi-Fi, fully digitized study resource terminal',
    transportation: 'Yes, university-operated transport systems covering Avadi and main Chennai terminals',
    roi: 'Average package 5.6 LPA',
    avgPlacementPackage: 5.6,
    uniquePoints: 'Massive residential campus with incredible student community, excellent sports facilities, and direct interface with leading healthcare recruiters.',
    loanDetails: 'Education loan processing supported via Bonafide Letter',
    scholarshipDetails: 'Tamil Nadu state online portal scholarship support',
    fstStaff: 'Naveen KS (9364148800) / Nivetha A (9003769158) / Priyanka TP',
    ismManager: 'Ankit'
  },
  {
    id: 'st-peters-bengaluru',
    name: "St. Peter's Institute of Higher Education and Research - Bengaluru",
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 10th 2026',
    region: 'South',
    state: 'Karnataka',
    city: 'Bengaluru',
    address: 'St Peters Campus, Off-Campus Terminal, Bengaluru, Karnataka 560001',
    lat: 12.9716,
    lng: 77.5946,
    mapUrl: 'https://maps.app.goo.gl/StPetersBLR',
    programsCount: 4,
    learnerIntake: 240,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5UshIlyY4jA',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Program fee: 7.5L (Total)',
    annualFee: 1.88,
    totalProgramFee: 7.5,
    paymentLink: 'St Peters Accounts Desk, Bengaluru',
    paymentCycle: 'Tuition paid in equal annual installments',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 PCB with 50% minimum',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Cardiovascular Technology (CVT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Standard off-campus hostel wings, 95k to 1.2 Lakhs/year)',
    amenity: 'Smart AV classrooms, student lounges, dedicated clinical labs',
    transportation: 'Yes, city-wide Bengaluru transport coverage',
    roi: 'Average package 5.8 LPA',
    avgPlacementPackage: 5.8,
    uniquePoints: 'Strategically located inside the medical and IT hub of Bengaluru - outstanding corporate interface and clinical internships.',
    loanDetails: 'Provides Bonafide letter; supported banks include Indian Bank, AXIS, or ICICI.',
    scholarshipDetails: 'Karnataka SSP state scholarship schemes',
    fstStaff: 'Suhana (8217388879) / Manasa RV (9902836394) / Sneha Dhanapal (7010808198)',
    ismManager: 'Ankit'
  },
  {
    id: 'st-marys-rehab',
    name: "St. Mary's Rehabilitation University",
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 15th 2026',
    region: 'South',
    state: 'Telangana',
    city: 'Hyderabad',
    address: 'Deshmukhi Village, Yadadri Bhuvanagiri District, Hyderabad, Telangana 508284',
    lat: 17.3482,
    lng: 78.7461,
    mapUrl: 'https://maps.app.goo.gl/StMarysRehab',
    programsCount: 4,
    learnerIntake: 200,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/g6j3aQoWzLk',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 25k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Program: 7.2L total structure',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'On-Campus Finance Desk',
    paymentCycle: 'Tuition structured on annual cycles',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Physiotherapy (BPT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (On-campus premium AC/Non-AC accommodations, average 1.1 Lakhs/year)',
    amenity: 'Motion capture analysis lab, massive 24/7 in-house clinic, student meditation gardens, full-sized sports courts',
    transportation: 'Yes, direct transport corridors across Hyderabad',
    roi: 'Average package 5.4 LPA',
    avgPlacementPackage: 5.4,
    uniquePoints: 'Specialized healthcare and clinical rehabilitation technologies institute with advanced kinematic modeling labs and smart classes.',
    loanDetails: 'Eligible for Vidya Lakshmi support; direct loan processing via Central Bank of India (Deshmukhi Branch)',
    scholarshipDetails: 'Telangana e-Kalyan state portal benefits',
    fstStaff: 'Arimanda Greeshma (6301955540) / Jyothi Vani (8247831991) / D Karthik',
    ismManager: 'Rahul'
  },
  {
    id: 'yenepoya',
    name: 'Yenepoya University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 15th 2026',
    region: 'South',
    state: 'Karnataka',
    city: 'Bengaluru',
    address: 'Yenepoya Campus, Hennur Road, Near outer ring road, Bengaluru, Karnataka 560043',
    lat: 13.0482,
    lng: 77.6241,
    mapUrl: 'https://maps.app.goo.gl/YenepoyaBLR',
    programsCount: 5,
    learnerIntake: 320,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5aox8NnIEnM',
    registrationFee: 'Application Fee - 1000 INR | Seat Booking is 26k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP courses: 8.4L Total Structure',
    annualFee: 2.1,
    totalProgramFee: 8.4,
    paymentLink: 'Yenepoya BLR Portal',
    paymentCycle: 'Paid per semester/annum',
    naacGrading: 'A+',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 with Biology, minimum 50% PCB aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Renal Dialysis Technology (B.RDT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Boys/Girls accommodations from 90,000 INR to 1,40,000 INR per year)',
    amenity: 'Direct integration with Yenepoya teaching hospital network, extensive nursing practice cells, wi-fi campus, digital study lounge',
    transportation: 'Yes, extensive bus route network across North/East Bengaluru',
    roi: 'Average package 6.5 LPA',
    avgPlacementPackage: 6.5,
    uniquePoints: 'NAAC A+ accredited university with absolute excellence in medicine, medical research, and on-site clinical internships.',
    loanDetails: 'Full bonafide support for executing national/private school student loans',
    scholarshipDetails: 'Yenepoya Foundation Merit Scholarships & Karnataka SSP Portal support',
    fstStaff: 'Prathiba J (9686057325)',
    ismManager: 'Rahul'
  },
  {
    id: 'presidency',
    name: 'Presidency University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 10th 2026',
    region: 'South',
    state: 'Karnataka',
    city: 'Bengaluru',
    address: 'Itgalpur Rajanakunte, Yelahanka, Bengaluru, Karnataka 560064',
    lat: 13.1679,
    lng: 77.5342,
    mapUrl: 'https://maps.app.goo.gl/PresidencyBLR',
    programsCount: 4,
    learnerIntake: 300,
    brochureLink: 'https://drive.google.com/drive/folders/1KpK8PfOU-AIwKKc1pmIPRsuUScfaNk6G?ths=true',
    campusVideo: 'https://www.youtube.com/embed/l5cgh-oP-jM',
    registrationFee: 'Application Fee is INR 1,500 | Booking Fees 30k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP course total: 8.0L Structure',
    annualFee: 2.0,
    totalProgramFee: 8.0,
    paymentLink: 'Presidency University Admissions Terminal',
    paymentCycle: 'Annum billing cycles',
    naacGrading: 'A+',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Capacity: 2000+ residents. Separate premium wings for boys/girls, fee 1,10,000 to 1,60,000/year)',
    amenity: 'Central modern playground, cafeteria court, fully enabled wi-fi, transport link with direct city BMTC connections',
    transportation: 'Yes, university-operated transport covering all cardinal coordinates of Bengaluru',
    roi: 'Average package 6.2 LPA',
    avgPlacementPackage: 6.2,
    uniquePoints: 'Ultra-advanced infrastructure with highly acclaimed placement office - tied up with leading global institutions for advanced learnings.',
    loanDetails: 'Direct ICICI Bank document linkage; bonafide documents provided for other banks',
    scholarshipDetails: 'Academic merit scholarship based on 10+2 marks and Karnataka state schemes',
    fstStaff: 'Direct Support Desk (See details)',
    ismManager: 'Rahul'
  },
  {
    id: 'arka-jain',
    name: 'Arka Jain University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 1st 2026',
    region: 'East',
    state: 'Jharkhand',
    city: 'Jamshedpur',
    address: 'Opp. To Kerala Public School, Mohanpur, Gamharia, Jamshedpur, Jharkhand 832108',
    lat: 22.8046,
    lng: 86.2029,
    mapUrl: 'https://maps.app.goo.gl/ArkaJainJamshedpur',
    programsCount: 4,
    learnerIntake: 250,
    brochureLink: 'https://drive.google.com/file/d/1wvDGIZRE2cdUTdIDGvr_yVvWqtilbcTh/view?usp=drive_link',
    campusVideo: 'https://www.youtube.com/embed/T00Oof68C3s',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Programs total: 6.4L',
    annualFee: 1.6,
    totalProgramFee: 6.4,
    paymentLink: 'Arka Jain Accounts desk online',
    paymentCycle: 'Semester-wise payment schedules',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Optometry (B.Optom)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Separate Girls and Boys hostels, 80k to 1.1 Lakhs/year)',
    amenity: 'Fully equipped modern clinical diagnostic practice cells, wi-fi campus, digital library systems, cafeteria, central lawn',
    transportation: 'Yes, comprehensive transport covering Jamshedpur region',
    roi: 'Average package 5.6 LPA',
    avgPlacementPackage: 5.6,
    uniquePoints: 'First premium private university in Jamshedpur, providing advanced state-of-the-art laboratory networks and highly dedicated training.',
    loanDetails: 'Vidyalakshmi scheme, GuruJi Student Credit Card scheme (Jharkhand Govt) and West Bengal Student Credit Card supported',
    scholarshipDetails: 'Jharkhand e-Kalyan Post-Matric Scholarship, AJUCET criteria discount scholarships',
    fstStaff: 'Neha Sharma (9113703120) / Dheeraj Kumar (7488032302)',
    ismManager: 'CCH-Manoj'
  },
  {
    id: 'kr-mangalam',
    name: 'K.R. Mangalam University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 25th 2026',
    region: 'North',
    state: 'Haryana',
    city: 'Gurugram',
    address: 'Sohna Road, Gurugram, Delhi NCR, Haryana 122103',
    lat: 28.3664,
    lng: 77.0617,
    mapUrl: 'https://maps.app.goo.gl/KRMangalamGurugram',
    programsCount: 5,
    learnerIntake: 280,
    brochureLink: 'https://drive.google.com/file/d/1YWczcX1RS6Udi9C9HQigMN4mPNUON_AI/view?usp=drive_link',
    campusVideo: 'https://www.youtube.com/embed/j_8q5Y9Hl5w',
    registrationFee: 'Application Fee is INR 1,500 | Booking Fees 25k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Course: 8.0L | Physiotherapy (BPT): 9.6L',
    annualFee: 2.0,
    totalProgramFee: 8.0,
    paymentLink: 'KR Mangalam Payment Gateways',
    paymentCycle: 'Tuition paid in equal annual installments',
    naacGrading: 'A',
    duration: '3+1 Years (AHP) | 4.5 Years (BPT)',
    eligibility: '10+2 Biology stream with 50% minimum',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Physiotherapy (BPT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Lush central AC double/triple sharing options, 1.4 Lakh to 1.8 Lakhs annually)',
    amenity: '4-times daily hygienic meals, laundry, gymnasium, fully AC halls, smart boards, Wi-Fi connectivity, central security guards',
    transportation: 'Yes, university bus network covering major Delhi NCR and Gurugram hubs',
    roi: 'Average package 6.5 LPA',
    avgPlacementPackage: 6.5,
    uniquePoints: 'Ultra-premium 5-star campus on Sohna road, tied up with top national hospital networks for high-intensity direct clinical training.',
    loanDetails: 'Tie-ups with leading financial authorities (ICICI, Axis, IDFC, multiple NBFCs), Vidyalakshmi Loan scheme',
    scholarshipDetails: 'Haryana state merit scholarships, discounts based on NEET/JEE or 12th PCB percentage',
    fstStaff: 'Kiran Gaud (8917079964) / Vishal Saroha (7027152986) / Ravi Das (9779769799)',
    ismManager: 'Syed Sahil'
  },
  {
    id: 'dbs-global',
    name: 'DBS Global University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 15th 2026',
    region: 'North',
    state: 'Uttarakhand',
    city: 'Dehradun',
    address: 'Selaqui, Dehradun, Uttarakhand 248011',
    lat: 30.3664,
    lng: 77.8524,
    mapUrl: 'https://maps.app.goo.gl/DBSGlobalUniversity',
    programsCount: 4,
    learnerIntake: 250,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/S2qTidN_rzo',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Programs total: 6.8L',
    annualFee: 1.7,
    totalProgramFee: 6.8,
    paymentLink: 'DBS Accounts Gateways online',
    paymentCycle: 'Annum billing cycles',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Modern hostel facilities, twin and single configurations, 95k to 1.3 Lakhs annually)',
    amenity: 'Central physics and robotic laboratories, e-library system, central cafeteria, sport lines',
    transportation: 'Yes, city-wide transit systems covering Dehradun region',
    roi: 'Average package 5.8 LPA',
    avgPlacementPackage: 5.8,
    uniquePoints: 'Nestled in the picturesque valley of Dehradun, featuring state-of-the-art infrastructure and highly focused placement records.',
    loanDetails: 'Bonafide letters issued for credit line approvals in nationalized and regional banks',
    scholarshipDetails: 'Uttarakhand domicile scholarship advantages up to 25% discount, Merit scholarships',
    fstStaff: 'Amit Mandal (8171969111)',
    ismManager: 'Syed Sahil'
  },
  {
    id: 'techno-india',
    name: 'Techno India University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 15th 2026',
    region: 'East',
    state: 'West Bengal',
    city: 'Kolkata',
    address: 'EM-4, Salt Lake Sector-V, Kolkata, West Bengal 700091',
    lat: 22.5786,
    lng: 88.4341,
    mapUrl: 'https://maps.app.goo.gl/TechnoIndiaKolkata',
    programsCount: 5,
    learnerIntake: 320,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/th-tCOwE3oM',
    registrationFee: 'Application Fee is INR 2,000 | Booking Fees 30k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Course struct: 7.2L - 8.0L Structure',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'Techno India Portal',
    paymentCycle: 'Semester-wise payment arrays',
    naacGrading: 'A',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 biological science PCB with 50% minimum',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Optometry (B.Optom)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Highly convenient PG networks in Sector-V corridor, average 70,000 to 95,000 INR/year)',
    amenity: 'Massive simulation labs, hi-tech digital classroom blocks, central server room, cafeteria, placement cell partners',
    transportation: 'Yes, city-wide Kolkata line routes',
    roi: 'Average package 5.9 LPA',
    avgPlacementPackage: 5.9,
    uniquePoints: 'Salt Lake Sector-V tech hub locate, first-class technical laboratories, stellar direct medical training tied with key medical cells.',
    loanDetails: 'West Bengal Student Credit Card Scheme supported (extremely popular, low-interest), bonafide letters provided',
    scholarshipDetails: 'West Bengal Swami Vivekananda Merit-cum-Means (SVMCM), Kanyashree Prakalpa, Aikyashree Minority Scholarship',
    fstStaff: 'Rinika Mukhopadhyay (8617286877) / Priyanka Roy (7872007742) / Manabendra Saha',
    ismManager: 'Ankit'
  },
  {
    id: 'lpu',
    name: 'Lovely Professional University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 10th 2026',
    region: 'North',
    state: 'Punjab',
    city: 'Phagwara',
    address: 'Jalandhar - Delhi, Grand Trunk Rd, Phagwara, Punjab 144411',
    lat: 31.2536,
    lng: 75.7037,
    mapUrl: 'https://maps.app.goo.gl/LPUPunjab',
    programsCount: 5,
    learnerIntake: 450,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5Fv38Gk_Qrs',
    registrationFee: 'Application Fee is INR 1,500 | Booking Fees 30k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP Programs: 8.0L Structure',
    annualFee: 2.0,
    totalProgramFee: 8.0,
    paymentLink: 'LPU admissions portal',
    paymentCycle: 'Annum/semester payments',
    naacGrading: 'A++',
    duration: '3+1 Years (AHP)',
    eligibility: 'Pass 10+2 with PCB (Minimum 50% Marks in Bio/Sciences)',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Physiotherapy (BPT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Accommodation for 4000+ residents managed by Pro-Bricks housing authority, 80k to 1.8 Lakhs/year)',
    amenity: 'Swimming pools, indoor game courts, cricket net practice field, air-conditioned corridors, RO systems, 24/7 security guards',
    transportation: 'Yes, university-operated transport covering Jalandhar-Phagwara-Ludhiana',
    roi: 'Average package 6.8 LPA',
    avgPlacementPackage: 6.8,
    uniquePoints: 'India’s largest single-campus private university, NAAC A++ accredited. Massive global student community, unparalleled recruitment drive.',
    loanDetails: 'Direct tie-up with nationalized banks (SBI, PNB) and leading NBFC credit lines; bonafide provided',
    scholarshipDetails: 'LPU NEST Entrance Scholarship, national portal benefits, and Punjab state schemes',
    fstStaff: 'Pallika Gaba (7009894808) / Silvia Sidana (7347228511) / Balwinder Kaur (9988246141)',
    ismManager: 'Syed Sahil'
  },
  {
    id: 'hcg-gha',
    name: 'HCG College of Allied Health Sciences And Academics (GHA Academy)',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 10th 2026',
    region: 'South',
    state: 'Karnataka',
    city: 'Bengaluru',
    address: 'HCG Towers, Double Road, Lalbagh, Bengaluru, Karnataka 560027',
    lat: 12.9602,
    lng: 77.5946,
    mapUrl: 'https://maps.app.goo.gl/HCGGHA',
    programsCount: 4,
    learnerIntake: 200,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5aox8NnIEnM',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP courses: 7.2L - 8.0L Structure',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'HCG on-site registry',
    paymentCycle: 'Semester-wise payment cycles',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 PCB with 50% minimum',
    programsList: [
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)',
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Convenient off-campus rentals, 80,000 to 1,10,000 INR/year)',
    amenity: 'Direct and exclusive clinical diagnostics learning at active HCG Oncology/General Hospitals, clinical diagnostic labs',
    transportation: 'Yes, transport links covering major Central BLR routes',
    roi: 'Average package 5.6 LPA',
    avgPlacementPackage: 5.6,
    uniquePoints: 'Operated by India’s leading healthcare chain - offering unparalleled direct hospital internship, live patient diagnosis, and job guarantees.',
    loanDetails: 'Bonafide letters issued for student bank credit processing',
    scholarshipDetails: 'NSP Portal and minority health scholarships applicable',
    fstStaff: 'Shubha Jain (7975256545) / Vishal S (7846801695) / Lalitha A (6366685337)',
    ismManager: 'Rahul'
  },
  {
    id: 'hcg-suchirayu',
    name: 'HCG Suchirayu College of Nursing',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 10th 2026',
    region: 'South',
    state: 'Karnataka',
    city: 'Hubballi',
    address: 'Gokul Road, Hubballi, Karnataka 580030',
    lat: 15.3647,
    lng: 75.1242,
    mapUrl: 'https://maps.app.goo.gl/HCGSuchirayu',
    programsCount: 3,
    learnerIntake: 180,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5aox8NnIEnM',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'Nursing & Allied: 6.4L structure',
    annualFee: 1.6,
    totalProgramFee: 6.4,
    paymentLink: 'Suchirayu Accounts Desk',
    paymentCycle: 'Annum billing cycles',
    naacGrading: 'NA',
    duration: '4 Years (BSc Nursing)',
    eligibility: '10+2 with Biology, minimum 45% PCB aggregate',
    programsList: [
      'B.Sc Nursing',
      'Bachelor of Medical Laboratory Science (MLS)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Girls accommodations only, 75,000 to 90,000 INR/year with secure boundary warden)',
    amenity: 'Connected with Suchirayu Teaching Hospital, safe girls-hostel blocks, Wi-Fi terminals',
    transportation: 'Yes, local Hubballi routes',
    roi: 'Average package 5.2 LPA',
    avgPlacementPackage: 5.2,
    uniquePoints: 'Specialized diagnostic and nursing block integrated with active multi-specialty Suchirayu Hospital, featuring direct real-time ICU practice.',
    loanDetails: 'Provides Bonafide letter for student educational loans with regional banks',
    scholarshipDetails: 'Karnataka state SSP schemes and regional nursing waivers',
    fstStaff: 'Gunaroopa Kotian (9916262674) / Madhura Sunit (8088547361)',
    ismManager: 'Rahul'
  },
  {
    id: 'maya-devi',
    name: 'Maya Devi University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 15th 2026',
    region: 'North',
    state: 'Uttarakhand',
    city: 'Dehradun',
    address: 'Selaqui, Dehradun, Uttarakhand 248011',
    lat: 30.3409,
    lng: 77.9514,
    mapUrl: 'https://maps.app.goo.gl/MayaDeviDehradun',
    programsCount: 4,
    learnerIntake: 220,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/thBG6VIutp8',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 15k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP courses: 6.8L',
    annualFee: 1.7,
    totalProgramFee: 6.8,
    paymentLink: 'Maya Devi Desk on campus',
    paymentCycle: 'Structured annum tuition schedules',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Scenic mountain view hostels, 90,000 to 1,20,000 INR/year)',
    amenity: 'Fully enabled digital labs, solar-powered campus blocks, scenic mountain views, robotics & culinary arts cells',
    transportation: 'Yes, bus routes across Dehradun valley',
    roi: 'Average package 5.5 LPA',
    avgPlacementPackage: 5.5,
    uniquePoints: 'Eco-responsible green campus in Dehradun, providing top-class clinical skill classes and extreme focus on physical diagnostic practice.',
    loanDetails: 'Bonafide letters issued for student loans with nationalized banks',
    scholarshipDetails: 'Uttarakhand state scholarship portal entries',
    fstStaff: 'Rani Gupta (9997241741)',
    ismManager: 'Syed Sahil'
  },
  {
    id: 'saraswati-group',
    name: 'Saraswati Group of Colleges',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 20th 2026',
    region: 'North',
    state: 'Punjab',
    city: 'Mohali',
    address: 'Chandigarh-Ludhiana Highway, Gharuan, Mohali, Punjab 140413',
    lat: 30.7046,
    lng: 76.7179,
    mapUrl: 'https://maps.app.goo.gl/SaraswatiGroup',
    programsCount: 4,
    learnerIntake: 240,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/u76anD4BQsY',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 15k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP total curriculum fee: 6.4L',
    annualFee: 1.6,
    totalProgramFee: 6.4,
    paymentLink: 'Saraswati Accounts offline',
    paymentCycle: 'Annum billing cycles',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: 'Pass 10+2 with PCB (Minimum 50% Marks in Bio/Sciences)',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Separate Girls and Boys rooms, fee from 80k per year)',
    amenity: 'Full Wi-Fi corridors, dining rooms, library access, smart AV classrooms, physical diagnostics cell',
    transportation: 'Yes, transport coverage for Mohali and Chandigarh cities',
    roi: 'Average package 5.4 LPA',
    avgPlacementPackage: 5.4,
    uniquePoints: 'Located directly along the Chandigarh-Ludhiana National Highway, offering convenient physical access, Wi-Fi smart classes, and deep placement tie-ups.',
    loanDetails: 'Supports educational loan requests via standard bonafide letters',
    scholarshipDetails: 'Punjab state scholarship schemes with tuition waivers for SC/ST',
    fstStaff: 'Amanpreet (9876143469) / Shobha Chauhan (8054711473)',
    ismManager: 'Syed Sahil'
  },
  {
    id: 'medhavi',
    name: 'Medhavi Skill University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 10th 2026',
    region: 'East',
    state: 'Sikkim',
    city: 'Sikkim',
    address: 'Singtam, Lower Chisopani, East Sikkim 737134',
    lat: 27.2354,
    lng: 88.4988,
    mapUrl: 'https://maps.app.goo.gl/MedhaviSikkim',
    programsCount: 4,
    learnerIntake: 200,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/S2qTidN_rzo',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP total structure: 6.4L',
    annualFee: 1.6,
    totalProgramFee: 6.4,
    paymentLink: 'Medhavi Accounts gates',
    paymentCycle: 'Installment options per year',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology space with 50% PCB minimum',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Lower Chisopani Singtam student blocks, 85,000 to 1,10,000 INR per year)',
    amenity: 'Advanced practical skill centers, multi-cuisine canteen, standard labs, wi-fi enabled study desks',
    transportation: 'Yes, local Sikkim highway transport support',
    roi: 'Average package 5.5 LPA',
    avgPlacementPackage: 5.5,
    uniquePoints: 'Specialized vocational and high-skill university, providing massive corporate apprentice systems and 100% focused placement loops.',
    loanDetails: 'Specialized skill-loan tie-ups, Vidyalakshmi scheme clearance supported',
    scholarshipDetails: 'Sikkim state board concessions via Medhavi Merit Entrance tests',
    fstStaff: 'Prashant Shukla (7985025869) / Asheesh Kumar (8239188527) / Lalit Kumar',
    ismManager: 'Unlisted'
  },
  {
    id: 'nehru-gram',
    name: 'Nehru Gram Bharati University',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'February 20th 2026',
    region: 'North',
    state: 'Uttar Pradesh',
    city: 'Allahabad',
    address: 'Kotwa, Jamunipur, Dubawal, Allahabad, Uttar Pradesh 221505',
    lat: 25.4358,
    lng: 81.8463,
    mapUrl: 'https://maps.app.goo.gl/NehruGramBharati',
    programsCount: 3,
    learnerIntake: 180,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/Da1s-Q8ie-8',
    registrationFee: 'Application Fee is INR 500 | Booking Fees 15k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP total course: 6.0L Structure',
    annualFee: 1.5,
    totalProgramFee: 6.0,
    paymentLink: 'NGBU Payment Office offline',
    paymentCycle: 'Annum/Installment payment arrays',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 Biology science stream with 50% minimum aggregate',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Medical Laboratory Science (MLS)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Jamunipur campus rooms, starting at 75k per year)',
    amenity: 'Peaceful green study environment, wi-fi terminals, comprehensive text reference libraries',
    transportation: 'Yes, direct transport wires covering Allahabad city',
    roi: 'Average package 5.2 LPA',
    avgPlacementPackage: 5.2,
    uniquePoints: 'Strong traditional academic grounding in Uttar Pradesh, featuring direct placement networks and deeply rooted diagnostic simulation centers.',
    loanDetails: 'Bonafide letters tracked for executing loans with regional cooperative banks',
    scholarshipDetails: 'UP state post-matric scholarship schemes and portal support',
    fstStaff: 'Ved Prakash Singh (8920848236)',
    ismManager: 'Unlisted'
  },
  {
    id: 'mvm-allied',
    name: 'MVM College of Allied Health Sciences',
    admissionStatus: 'Admission 2026 Open',
    admissionStartDate: 'January 10th 2026',
    region: 'South',
    state: 'Karnataka',
    city: 'Bengaluru',
    address: 'Airport Road, Palanahalli, Yelahanka, Bengaluru, Karnataka 560064',
    lat: 13.0854,
    lng: 77.6094,
    mapUrl: 'https://maps.app.goo.gl/MVMAllied',
    programsCount: 5,
    learnerIntake: 260,
    brochureLink: '',
    campusVideo: 'https://www.youtube.com/embed/5aox8NnIEnM',
    registrationFee: 'Application Fee is INR 1,000 | Booking Fees 20k',
    bridgeFee: '30,000 INR Non-Refundable Bridge Course Fee',
    programFee: 'AHP total structure: 7.2L - 8.0L Structure',
    annualFee: 1.8,
    totalProgramFee: 7.2,
    paymentLink: 'MVM Bengaluru Admissions Office',
    paymentCycle: 'Annual Tuition structures',
    naacGrading: 'NA',
    duration: '3+1 Years (AHP)',
    eligibility: '10+2 with PCB (Minimum 50% Marks in Bio/Sciences)',
    programsList: [
      'Bachelor of ANAESTHESIA & OPERATION THEATRE TECHNOLOGY (A&OTT)',
      'Bachelor of Cardiovascular Technology (CVT)',
      'Bachelor of Medical Laboratory Science (MLS)',
      'Bachelor of Medical Radiology and Imaging Technology (B.MRIT)'
    ],
    universityOwner: 'N/A',
    campusManager: 'N/A',
    hostelAvailable: 'Yes (Palanahalli wings, separateBoys/Girls blocks, starting from 90,000 INR/year)',
    amenity: 'Advanced clinical diagnostic rooms, multi-cuisine cafeteria, Wi-Fi smart classrooms, direct placement labs',
    transportation: 'Yes, transport covering major North Bengaluru routes',
    roi: 'Average package 5.6 LPA',
    avgPlacementPackage: 5.6,
    uniquePoints: 'Located centrally along Bengaluru Airport road - features outstanding practical diagnostic setups and intense training facilities.',
    loanDetails: 'Offers complete bonafide letter support for student bank credit processing with Axis/ICICI',
    scholarshipDetails: 'Karnataka State SSP portal schemes and national portal benefits',
    fstStaff: 'Arshad Ali (9620418133)',
    ismManager: 'Rahul'
  }
];

export const POPULAR_LOCATIONS: { [key: string]: { name: string; lat: number; lng: number; pincodes: string[] } } = {
  pune: {
    name: 'Pune, Maharashtra',
    lat: 18.5204,
    lng: 73.8567,
    pincodes: ['411057', '411001', '411002', '411014', '411045', '411038', '411019', '412306', '412307', '411005', '412105']
  },
  mumbai: {
    name: 'Mumbai/Vasai, Maharashtra',
    lat: 19.0760,
    lng: 72.8777,
    pincodes: ['400001', '400002', '400050', '400097', '401208', '401201', '401202', '400072']
  },
  kopargaon: {
    name: 'Kopargaon/Ahilyanagar, Maharashtra',
    lat: 19.9010,
    lng: 74.4949,
    pincodes: ['423601', '423602', '414001', '414002']
  },
  indore: {
    name: 'Indore, Madhya Pradesh',
    lat: 22.7196,
    lng: 75.8577,
    pincodes: ['452001', '452002', '453331', '452010', '452016']
  }
};

// Haversine formula to compute geodesic distance between two coordinate pairs
export function getHaversineDistance(lat1: number, lng1: number, lat2: number, lng2: number): number {
  const R = 6371; // Earth's radius in kilometers
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLng = ((lng2 - lng1) * Math.PI) / 180;
  
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLng / 2) *
      Math.sin(dLng / 2);
      
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c); // Distance in km
}

// Map the first 2 digits of a pincode to approximate states in India if not found in POPULAR_LOCATIONS
export function getCoordinatesFromPincode(pincode: string): { name: string; lat: number; lng: number } | null {
  const cleanPin = pincode.trim().replace(/\s+/g, '');
  
  // 1. Search directly in pop locations pincode array
  for (const key of Object.keys(POPULAR_LOCATIONS)) {
    const loc = POPULAR_LOCATIONS[key];
    if (loc.pincodes.some(p => p.startsWith(cleanPin.substring(0, 6)) || cleanPin.startsWith(p))) {
      return {
        name: `Pincode ${pincode} (${loc.name.split(',')[0]} Region)`,
        lat: loc.lat,
        lng: loc.lng
      };
    }
  }
  
  // 2. Structural Pincode Prefix Map (Dynamic India Geocoder heuristic)
  if (cleanPin.length >= 2) {
    const prefix2 = cleanPin.substring(0, 2);
    const prefixNum = parseInt(prefix2, 10);
    
    if (prefixNum >= 11 && prefixNum <= 13) {
      return { name: `Pincode ${pincode} (Delhi NCR Region)`, lat: 28.6139, lng: 77.2090 };
    } else if (prefixNum >= 14 && prefixNum <= 16) {
      return { name: `Pincode ${pincode} (Punjab/Haryana Region)`, lat: 30.7333, lng: 76.7794 };
    } else if (prefixNum === 17) {
      return { name: `Pincode ${pincode} (Himachal Region)`, lat: 31.1048, lng: 77.1734 };
    } else if (prefixNum >= 18 && prefixNum <= 19) {
      return { name: `Pincode ${pincode} (J&K Region)`, lat: 34.0837, lng: 74.7973 };
    } else if (prefixNum >= 20 && prefixNum <= 28) {
      // 24 is Uttarakhand, 20-28 is UP
      if (prefixNum === 24) {
        return { name: `Pincode ${pincode} (Dehradun, UK Region)`, lat: 30.3165, lng: 78.0322 };
      }
      return { name: `Pincode ${pincode} (Uttar Pradesh Region)`, lat: 26.8467, lng: 80.9462 };
    } else if (prefixNum >= 30 && prefixNum <= 34) {
      return { name: `Pincode ${pincode} (Rajasthan Region)`, lat: 26.9124, lng: 75.7873 };
    } else if (prefixNum >= 36 && prefixNum <= 39) {
      return { name: `Pincode ${pincode} (Gujarat Region)`, lat: 23.0225, lng: 72.5714 };
    } else if (prefixNum >= 40 && prefixNum <= 44) {
      // Maharashtra
      if (cleanPin.startsWith('413')) {
        return { name: `Pincode ${pincode} (Solapur Region)`, lat: 17.6599, lng: 75.9064 };
      } else if (cleanPin.startsWith('411') || cleanPin.startsWith('412')) {
        return { name: `Pincode ${pincode} (Pune Region)`, lat: 18.5204, lng: 73.8567 };
      }
      return { name: `Pincode ${pincode} (Maharashtra Region)`, lat: 19.7515, lng: 75.7139 };
    } else if (prefixNum >= 45 && prefixNum <= 49) {
      return { name: `Pincode ${pincode} (Madhya Pradesh Region)`, lat: 22.7196, lng: 75.8577 };
    } else if (prefixNum >= 50 && prefixNum <= 53) {
      // Telangana/AP
      if (cleanPin.startsWith('502')) {
        return { name: `Pincode ${pincode} (Sangareddy Telangana)`, lat: 17.6253, lng: 78.0494 };
      }
      return { name: `Pincode ${pincode} (Telangana Region)`, lat: 17.3850, lng: 78.4867 };
    } else if (prefixNum >= 56 && prefixNum <= 59) {
      // Karnataka
      if (cleanPin.startsWith('580')) {
        return { name: `Pincode ${pincode} (Hubballi Region)`, lat: 15.3647, lng: 75.1242 };
      }
      return { name: `Pincode ${pincode} (Bengaluru Region)`, lat: 12.9716, lng: 77.5946 };
    } else if (prefixNum >= 60 && prefixNum <= 64) {
      return { name: `Pincode ${pincode} (Tamil Nadu Region)`, lat: 13.0827, lng: 80.2707 };
    } else if (prefixNum >= 70 && prefixNum <= 74) {
      // WB / Sikkim
      if (cleanPin.startsWith('737')) {
        return { name: `Pincode ${pincode} (Sikkim Region)`, lat: 27.2354, lng: 88.4988 };
      }
      return { name: `Pincode ${pincode} (Kolkata Region)`, lat: 22.5726, lng: 88.3639 };
    } else if (prefixNum >= 75 && prefixNum <= 77) {
      return { name: `Pincode ${pincode} (Odisha Region)`, lat: 20.2961, lng: 85.8245 };
    } else if (prefixNum >= 78 && prefixNum <= 79) {
      return { name: `Pincode ${pincode} (North East Region)`, lat: 26.1445, lng: 91.7362 };
    } else if (prefixNum >= 80 && prefixNum <= 85) {
      if (cleanPin.startsWith('831') || cleanPin.startsWith('832')) {
        return { name: `Pincode ${pincode} (Jamshedpur/JH)`, lat: 22.8046, lng: 86.2029 };
      }
      return { name: `Pincode ${pincode} (Jharkhand/Bihar)`, lat: 23.3441, lng: 85.3091 };
    }
  }
  
  // Standard Default (Center of India - Nagpur) if nothing else works
  return { name: `Pincode ${pincode} (General India)`, lat: 21.1458, lng: 79.0882 };
}
